### Recuperar todas las películas
GET http://localhost:1234/movies

### Rescuperar una película por id
GET http://localhost:1234/movies/d5df97e5-cb1f-4702-aca6-7a978ab3f7e7

### Recuperar todas las películas por un género
GET http://localhost:1234/movies?genre=Romance



### Crear una película
POST http://localhost:1234/movies
Content-type: application/json

{
    "title" : "lost5",
    "year" : 2022,
    "director": "Francis Ford Coppolaa",
    "duration" : 171,
    "poster": "https://brattlefilm.org/movies/the-godfather/",
    "genre" : ["Crime", "Drama", "Action"]
}

### Actualizar una película
PATCH http://localhost:1234/movies/e3b4c2da-bbd3-47a2-b3f4-ca370e829f79
Content-type: application/json

{
    "year" : 1962
    

    
}

### Eliminar una película
DELETE http://localhost:1234/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf